version: '3'

services:
  redis:
    image: redis:alpine
    container_name: vietnam_laws_redis_db
    volumes:
      - database:/data/redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - vietnam-laws-network
    restart: always

  postgres:
    image: postgres:14
    container_name: vietnam_laws_db
    command: postgres -c 'max_connections=200'
    volumes:
      - database:/data/postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - vietnam-laws-network
    restart: always

networks:
  vietnam-laws-network:
    name: vietnam-laws-network
    driver: bridge

volumes:
  database:
