version: "3"

services:
  redis:
    image: redis:alpine
    container_name: vietnam_laws_redis_db
    volumes:
      - database:/data/redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - vietnam-laws-network
    restart: always

  mysql:
    image: mysql:5.7
    container_name: vietnam_laws_mysql_db
    volumes:
      - database:/data/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - vietnam-laws-network
    restart: always

networks:
  vietnam-laws-network:
    name: vietnam-laws-network
    driver: bridge

volumes:
  database: