name: VLA BE Service Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare the environments
      run: make prepare-environments
    - name: Build the Docker image
      run: docker compose up -d
